# Generated by Django 4.2.5 on 2023-10-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unread'), (1, 'Reading'), (2, 'Read'), (-1, 'Unknown')], default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
