# Generated by Django 4.2.5 on 2023-10-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0002_book_status_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unread'), (1, 'Reading'), (2, 'Read'), (-1, 'Unknown')], default=-1),
        ),
    ]
